// Generated by https://quicktype.io

export interface LoginUser {
    user:         User;
    accessToken:  string;
    refreshToken: string;
}

export interface User {
    id?:          string;
    gender?:      string;
    name:         string;
    cpf?:         string;
    passport?:    string;
    email:        string;
    emailActive:  boolean;
    dateBirth:    string;
    phone:        string;
    address?:     any[];
    posts?:       any[];
    role?:        string;
    createdAt?:   string;
    password?:    string;
    rvLength?:    number;
    rvPlate?:     string;
    tugPlate?:    string;
    touristType:  string;
    vehicleType:  string;

}
