export const RULES = [
  { name: 'Banheiro', icon: 'fa-toilet', code: 'BAN' },
  { name: 'Chuveiro com água quente', icon: 'fa-shower', code: 'CHV' },
  { name: 'Água', icon: 'fa-tint', code: 'AGU' },
  { name: 'Eletricidade', icon: 'fa-plug', code: 'ELE' },
  { name: 'Local para descarte de detrito', icon: 'fa-trash', code: 'LDD' },
  { name: 'Wi-fi', icon: 'fa-wifi', code: 'WIFI' },
  { name: 'Pet friendly', icon: 'fa-paw', code: 'PET' },
  { name: 'Churrasqueira', icon: 'fa-fire', code: 'CHU' },
  { name: 'Cozinha externa', icon: 'fa-utensils', code: 'COZ' },
  { name: 'Quiosques', icon: 'fa-umbrella-beach', code: 'QUI' },
  { name: 'Quadra/campo de esportes', icon: 'fa-futbol', code: 'ESP' },
  { name: 'Piscina', icon: 'fa-swimming-pool', code: 'PIC' },
  { name: 'Playground', icon: 'fa-child', code: 'PLG' },
  { name: 'Restaurante', icon: 'fa-utensils', code: 'RES' },
  { name: 'Lanchonete', icon: 'fa-hamburger', code: 'LAN' },
  { name: 'Lavanderia', icon: 'fa-washer', code: 'LAV' },
  { name: 'Loja de conveniências', icon: 'fa-store', code: 'LOJ' },
  { name: 'Sala de Jogos', icon: 'fa-gamepad', code: 'SAJ' },
  { name: 'Esportes aquáticos', icon: 'fa-swimmer', code: 'EQA' },
  { name: 'Local para trilhas', icon: 'fa-hiking', code: 'LTR' },
  { name: 'Passeios à cavalo', icon: 'fa-horse', code: 'PCA' },
  { name: 'Passeios diversos', icon: 'fa-walking', code: 'PDI' },
  { name: 'Aluguel de bikes', icon: 'fa-bicycle', code: 'ALB' },
  { name: 'Pesca esportiva', icon: 'fa-fish', code: 'PES' },
  { name: 'Day use', icon: 'fa-sun', code: 'DUS' },
  { name: 'Massagens terapêuticas', icon: 'fa-spa', code: 'MAS' },
  { name: 'Cachoeira', icon: 'fa-waterfall', code: 'CAC' },
  { name: 'Tirolesa', icon: 'fa-zipline', code: 'TIR' },
  { name: 'Fogueira', icon: 'fa-campfire', code: 'FOG' },
  { name: 'Complexo Turístico de lazer', icon: 'fa-hotel', code: 'CTL' },
  { name: 'Turismo Religioso', icon: 'fa-church', code: 'TUR' },
  { name: 'Ecoturismo', icon: 'fa-tree', code: 'ECO' },
  { name: 'Turismo de aventura', icon: 'fa-mountain', code: 'TAV' },
  { name: 'Turismo de Compras', icon: 'fa-shopping-bag', code: 'TCO' },
  {
    name: 'Parque Nacional/Estadual/Municipal',
    icon: 'fa-tree',
    code: 'PNM',
  },
  { name: 'Rural', icon: 'fa-tractor', code: 'RUR' },
  { name: 'Destino Urbano', icon: 'fa-city', code: 'DUR' },
  { name: 'Praia', icon: 'fa-beach', code: 'PRA' },
  { name: 'Beira Mar', icon: 'fa-water', code: 'BEM' },
  { name: 'Lagoa', icon: 'fa-water', code: 'LAG' },
  { name: 'Vinícola', icon: 'fa-wine-bottle', code: 'VIN' },
  { name: 'Aceita eventos', icon: 'fa-calendar-alt', code: 'ACE' },
];
